# Generated by Django 6.0.7 on 2026-07-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Espejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True, help_text='Visibilidad en el catálogo público')),
                ('destacado', models.BooleanField(default=False, help_text='Destacar en catálogo / portada')),
                ('forma', models.CharField(choices=[('redondo', 'Redondo'), ('ovalado', 'Ovalado'), ('rectangular', 'Rectangular'), ('arco', 'Arco')], default='redondo', max_length=20)),
                ('temperatura_min_k', models.PositiveIntegerField(default=3000, help_text='Temperatura mínima en Kelvin (ej. 2700)')),
                ('temperatura_max_k', models.PositiveIntegerField(default=6500, help_text='Temperatura máxima en Kelvin (ej. 6500)')),
                ('regulable', models.BooleanField(default=True, verbose_name='Luz Regulable / Dimmable')),
                ('antivaho', models.BooleanField(default=False, verbose_name='Sistema Antivaho Integated')),
                ('ancho_cm', models.PositiveIntegerField(help_text='Ancho en centímetros')),
                ('alto_cm', models.PositiveIntegerField(help_text='Alto en centímetros')),
                ('stock', models.PositiveIntegerField(default=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espejos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Espejo',
                'verbose_name_plural': 'Espejos',
                'ordering': ['-destacado', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('espejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.espejo')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mensaje', models.TextField(blank=True)),
                ('canal', models.CharField(choices=[('formulario', 'Formulario Web'), ('whatsapp', 'WhatsApp')], default='formulario', max_length=20)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('espejo_interes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalogo.espejo', verbose_name='Espejo de Interés')),
            ],
            options={
                'verbose_name': 'Lead / Interesado',
                'verbose_name_plural': 'Leads / Interesados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
