# Generated by Django 6.0.7 on 2026-07-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_eyebrow', models.CharField(default='ILUMINACIÓN ARQUITECTÓNICA & TECNOLOGÍA', max_length=150, verbose_name='Texto pequeño superior (Eyebrow)')),
                ('titulo_principal', models.CharField(default='La Luz que Enciende tu Espacio', help_text='Consejo: Usa etiquetas HTML simples como <em>tu espacio</em> para resaltar en degradado LED', max_length=200, verbose_name='Título del Hero')),
                ('subtitulo', models.TextField(default='Espejos de diseño superior con iluminación LED perimetral integrada, dial de temperatura Kelvin regulable y cristal con defroster antivaho.', verbose_name='Subtítulo descriptivo')),
                ('imagen_hero', models.ImageField(blank=True, help_text='📐 TAMAÑO RECOMENDADO: Proporción 1:1 cuadrada (ej. 800x800px o 1000x1000px). Formato PNG transparente o JPG con fondo oscuro (#111318). Al subir la imagen, asegúrate de elegir el encuadre para evitar recortes desalineados.', null=True, upload_to='hero/', verbose_name='Imagen del Espejo Hero')),
                ('posicion_imagen', models.CharField(choices=[('center center', 'Centrado perfecto (Center Center)'), ('top center', 'Alineado arriba (Top Center)'), ('bottom center', 'Alineado abajo (Bottom Center)'), ('center left', 'Alineado izquierda (Center Left)'), ('center right', 'Alineado derecha (Center Right)')], default='center center', help_text='Define el punto focal para que la imagen quede centrada o alineada a tu gusto.', max_length=30, verbose_name='Alineación/Posicionamiento de Imagen (Object-Position)')),
                ('ajuste_imagen', models.CharField(choices=[('contain', 'Ajustar Completo (Contain - No recortar nada, mantener entero)'), ('cover', 'Cubrir Todo el Marco (Cover - Llenar completo)')], default='contain', help_text="Usa 'Contain' para que la imagen se vea 100% entera sin ningún corte.", max_length=20, verbose_name='Modo de Ajuste (Object-Fit)')),
                ('activo', models.BooleanField(default=True, verbose_name='Hero Activo en Portada')),
                ('espejo_vinculado', models.ForeignKey(blank=True, help_text='Vincular a la ficha técnica de un espejo del catálogo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.espejo', verbose_name='Espejo Vinculado (Opcional)')),
            ],
            options={
                'verbose_name': 'Configuración del Hero Parallax',
                'verbose_name_plural': 'Configuraciones del Hero Parallax',
            },
        ),
    ]
